USE [master]
GO
/****** Object:  Database [Google]    Script Date: 14/5/2018 17:53:21 ******/
CREATE DATABASE [Google]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Google', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Google.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Google_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Google_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Google] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Google].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Google] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Google] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Google] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Google] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Google] SET ARITHABORT OFF 
GO
ALTER DATABASE [Google] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Google] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Google] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Google] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Google] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Google] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Google] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Google] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Google] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Google] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Google] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Google] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Google] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Google] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Google] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Google] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Google] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Google] SET RECOVERY FULL 
GO
ALTER DATABASE [Google] SET  MULTI_USER 
GO
ALTER DATABASE [Google] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Google] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Google] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Google] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Google] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Google', N'ON'
GO
ALTER DATABASE [Google] SET QUERY_STORE = OFF
GO
USE [Google]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Google]
GO
/****** Object:  Table [dbo].[Rese?as]    Script Date: 14/5/2018 17:53:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rese?as](
	[Texto] [varchar](500) NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Google] SET  READ_WRITE 
GO







USE Google

DECLARE @json VARCHAR(MAX)
SELECT @json = BulkColumn
FROM OPENROWSET (BULK 'C:\Users\Rubén González V\OneDrive\TEC\3 Semestre\Analisis de Algoritmos\mini-browser\1000.json', SINGLE_CLOB) as j

Insert Into dbo.Reseñas Select *
FROM OPENJSON(@json)
WITH (   
	Texto  varchar(100) '$.reviewText'
 ) 
